version: "2"

services:
  symfony:
    image: touch4it/php8:php8.2-fpm-nginx-dev
    volumes:
      - ./symfony:/var/www/html:cached
      - ./symfony/entrypoint.sh:/entrypoint.sh
      - ./symfony/nginx.conf:/etc/nginx/nginx.conf
      - ./symfony/nginx.default.conf:/etc/nginx/conf.d/default.conf
      - ./symfony/php.ini:/usr/local/etc/php/conf.d/docker-vars.ini
    ports:
      - 8080:80

  mysql:
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
      - ./mysql/data:/var/lib/mysql
    ports:
      - 3306:3306

  # firefox:
  #   image: selenium/standalone-firefox:118.0
  #   ports:
  #     - 4444
  #     - 5900