doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '15'

        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci

        profiling_collect_backtrace: '%kernel.debug%'
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Content:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Content/Infrastructure/Persistence/Doctrine/Entity'
                prefix: 'App\Content\Domain\Model'
                alias: 'App\Content\Domain\Model'
            Blog:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Content/Blog/Infrastructure/Persistence/Doctrine/Entity'
                prefix: 'App\Content\Blog\Domain\Model'
                alias: 'App\Content\Blog\Domain\Model'
            Comment:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Content/Comment/Infrastructure/Persistence/Doctrine/Entity'
                prefix: 'App\Content\Comment\Domain\Model'
                alias: 'App\Content\Comment\Domain\Model'
            UserProfile:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/UserProfile/Infrastructure/Persistence/Doctrine/Entity'
                prefix: 'App\UserProfile\Domain\Model'
                alias: 'App\UserProfile\Domain\Model'

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
